// Generated by gencpp from file eve_main/EndEffectorPosition.msg
// DO NOT EDIT!


#ifndef EVE_MAIN_MESSAGE_ENDEFFECTORPOSITION_H
#define EVE_MAIN_MESSAGE_ENDEFFECTORPOSITION_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace eve_main
{
template <class ContainerAllocator>
struct EndEffectorPosition_
{
  typedef EndEffectorPosition_<ContainerAllocator> Type;

  EndEffectorPosition_()
    : xPosition(0.0)
    , yPosition(0.0)
    , zPosition(0.0)  {
    }
  EndEffectorPosition_(const ContainerAllocator& _alloc)
    : xPosition(0.0)
    , yPosition(0.0)
    , zPosition(0.0)  {
  (void)_alloc;
    }



   typedef float _xPosition_type;
  _xPosition_type xPosition;

   typedef float _yPosition_type;
  _yPosition_type yPosition;

   typedef float _zPosition_type;
  _zPosition_type zPosition;





  typedef boost::shared_ptr< ::eve_main::EndEffectorPosition_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::eve_main::EndEffectorPosition_<ContainerAllocator> const> ConstPtr;

}; // struct EndEffectorPosition_

typedef ::eve_main::EndEffectorPosition_<std::allocator<void> > EndEffectorPosition;

typedef boost::shared_ptr< ::eve_main::EndEffectorPosition > EndEffectorPositionPtr;
typedef boost::shared_ptr< ::eve_main::EndEffectorPosition const> EndEffectorPositionConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::eve_main::EndEffectorPosition_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::eve_main::EndEffectorPosition_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::eve_main::EndEffectorPosition_<ContainerAllocator1> & lhs, const ::eve_main::EndEffectorPosition_<ContainerAllocator2> & rhs)
{
  return lhs.xPosition == rhs.xPosition &&
    lhs.yPosition == rhs.yPosition &&
    lhs.zPosition == rhs.zPosition;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::eve_main::EndEffectorPosition_<ContainerAllocator1> & lhs, const ::eve_main::EndEffectorPosition_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace eve_main

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::eve_main::EndEffectorPosition_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::eve_main::EndEffectorPosition_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::eve_main::EndEffectorPosition_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::eve_main::EndEffectorPosition_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::eve_main::EndEffectorPosition_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::eve_main::EndEffectorPosition_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::eve_main::EndEffectorPosition_<ContainerAllocator> >
{
  static const char* value()
  {
    return "f98d79514754ade5731789b7227e61f3";
  }

  static const char* value(const ::eve_main::EndEffectorPosition_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xf98d79514754ade5ULL;
  static const uint64_t static_value2 = 0x731789b7227e61f3ULL;
};

template<class ContainerAllocator>
struct DataType< ::eve_main::EndEffectorPosition_<ContainerAllocator> >
{
  static const char* value()
  {
    return "eve_main/EndEffectorPosition";
  }

  static const char* value(const ::eve_main::EndEffectorPosition_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::eve_main::EndEffectorPosition_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 xPosition\n"
"float32 yPosition\n"
"float32 zPosition\n"
;
  }

  static const char* value(const ::eve_main::EndEffectorPosition_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::eve_main::EndEffectorPosition_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.xPosition);
      stream.next(m.yPosition);
      stream.next(m.zPosition);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct EndEffectorPosition_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::eve_main::EndEffectorPosition_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::eve_main::EndEffectorPosition_<ContainerAllocator>& v)
  {
    s << indent << "xPosition: ";
    Printer<float>::stream(s, indent + "  ", v.xPosition);
    s << indent << "yPosition: ";
    Printer<float>::stream(s, indent + "  ", v.yPosition);
    s << indent << "zPosition: ";
    Printer<float>::stream(s, indent + "  ", v.zPosition);
  }
};

} // namespace message_operations
} // namespace ros

#endif // EVE_MAIN_MESSAGE_ENDEFFECTORPOSITION_H
