// Generated by gencpp from file eve_main/GoToPosition.msg
// DO NOT EDIT!


#ifndef EVE_MAIN_MESSAGE_GOTOPOSITION_H
#define EVE_MAIN_MESSAGE_GOTOPOSITION_H

#include <ros/service_traits.h>


#include <eve_main/GoToPositionRequest.h>
#include <eve_main/GoToPositionResponse.h>


namespace eve_main
{

struct GoToPosition
{

typedef GoToPositionRequest Request;
typedef GoToPositionResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GoToPosition
} // namespace eve_main


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::eve_main::GoToPosition > {
  static const char* value()
  {
    return "c8d13069b95fb9c6b68d27613e61705e";
  }

  static const char* value(const ::eve_main::GoToPosition&) { return value(); }
};

template<>
struct DataType< ::eve_main::GoToPosition > {
  static const char* value()
  {
    return "eve_main/GoToPosition";
  }

  static const char* value(const ::eve_main::GoToPosition&) { return value(); }
};


// service_traits::MD5Sum< ::eve_main::GoToPositionRequest> should match
// service_traits::MD5Sum< ::eve_main::GoToPosition >
template<>
struct MD5Sum< ::eve_main::GoToPositionRequest>
{
  static const char* value()
  {
    return MD5Sum< ::eve_main::GoToPosition >::value();
  }
  static const char* value(const ::eve_main::GoToPositionRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::eve_main::GoToPositionRequest> should match
// service_traits::DataType< ::eve_main::GoToPosition >
template<>
struct DataType< ::eve_main::GoToPositionRequest>
{
  static const char* value()
  {
    return DataType< ::eve_main::GoToPosition >::value();
  }
  static const char* value(const ::eve_main::GoToPositionRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::eve_main::GoToPositionResponse> should match
// service_traits::MD5Sum< ::eve_main::GoToPosition >
template<>
struct MD5Sum< ::eve_main::GoToPositionResponse>
{
  static const char* value()
  {
    return MD5Sum< ::eve_main::GoToPosition >::value();
  }
  static const char* value(const ::eve_main::GoToPositionResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::eve_main::GoToPositionResponse> should match
// service_traits::DataType< ::eve_main::GoToPosition >
template<>
struct DataType< ::eve_main::GoToPositionResponse>
{
  static const char* value()
  {
    return DataType< ::eve_main::GoToPosition >::value();
  }
  static const char* value(const ::eve_main::GoToPositionResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // EVE_MAIN_MESSAGE_GOTOPOSITION_H
