// Generated by gencpp from file eve_main/GoToPositionRequest.msg
// DO NOT EDIT!


#ifndef EVE_MAIN_MESSAGE_GOTOPOSITIONREQUEST_H
#define EVE_MAIN_MESSAGE_GOTOPOSITIONREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace eve_main
{
template <class ContainerAllocator>
struct GoToPositionRequest_
{
  typedef GoToPositionRequest_<ContainerAllocator> Type;

  GoToPositionRequest_()
    : desiredXPosition(0.0)
    , desiredZPosition(0.0)
    , speed(0.0)  {
    }
  GoToPositionRequest_(const ContainerAllocator& _alloc)
    : desiredXPosition(0.0)
    , desiredZPosition(0.0)
    , speed(0.0)  {
  (void)_alloc;
    }



   typedef float _desiredXPosition_type;
  _desiredXPosition_type desiredXPosition;

   typedef float _desiredZPosition_type;
  _desiredZPosition_type desiredZPosition;

   typedef float _speed_type;
  _speed_type speed;





  typedef boost::shared_ptr< ::eve_main::GoToPositionRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::eve_main::GoToPositionRequest_<ContainerAllocator> const> ConstPtr;

}; // struct GoToPositionRequest_

typedef ::eve_main::GoToPositionRequest_<std::allocator<void> > GoToPositionRequest;

typedef boost::shared_ptr< ::eve_main::GoToPositionRequest > GoToPositionRequestPtr;
typedef boost::shared_ptr< ::eve_main::GoToPositionRequest const> GoToPositionRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::eve_main::GoToPositionRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::eve_main::GoToPositionRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::eve_main::GoToPositionRequest_<ContainerAllocator1> & lhs, const ::eve_main::GoToPositionRequest_<ContainerAllocator2> & rhs)
{
  return lhs.desiredXPosition == rhs.desiredXPosition &&
    lhs.desiredZPosition == rhs.desiredZPosition &&
    lhs.speed == rhs.speed;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::eve_main::GoToPositionRequest_<ContainerAllocator1> & lhs, const ::eve_main::GoToPositionRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace eve_main

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::eve_main::GoToPositionRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::eve_main::GoToPositionRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::eve_main::GoToPositionRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::eve_main::GoToPositionRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::eve_main::GoToPositionRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::eve_main::GoToPositionRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::eve_main::GoToPositionRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "c8d13069b95fb9c6b68d27613e61705e";
  }

  static const char* value(const ::eve_main::GoToPositionRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xc8d13069b95fb9c6ULL;
  static const uint64_t static_value2 = 0xb68d27613e61705eULL;
};

template<class ContainerAllocator>
struct DataType< ::eve_main::GoToPositionRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "eve_main/GoToPositionRequest";
  }

  static const char* value(const ::eve_main::GoToPositionRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::eve_main::GoToPositionRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 desiredXPosition\n"
"float32 desiredZPosition\n"
"float32 speed\n"
;
  }

  static const char* value(const ::eve_main::GoToPositionRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::eve_main::GoToPositionRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.desiredXPosition);
      stream.next(m.desiredZPosition);
      stream.next(m.speed);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GoToPositionRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::eve_main::GoToPositionRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::eve_main::GoToPositionRequest_<ContainerAllocator>& v)
  {
    s << indent << "desiredXPosition: ";
    Printer<float>::stream(s, indent + "  ", v.desiredXPosition);
    s << indent << "desiredZPosition: ";
    Printer<float>::stream(s, indent + "  ", v.desiredZPosition);
    s << indent << "speed: ";
    Printer<float>::stream(s, indent + "  ", v.speed);
  }
};

} // namespace message_operations
} // namespace ros

#endif // EVE_MAIN_MESSAGE_GOTOPOSITIONREQUEST_H
