// Generated by gencpp from file eve_main/HomeY.msg
// DO NOT EDIT!


#ifndef EVE_MAIN_MESSAGE_HOMEY_H
#define EVE_MAIN_MESSAGE_HOMEY_H

#include <ros/service_traits.h>


#include <eve_main/HomeYRequest.h>
#include <eve_main/HomeYResponse.h>


namespace eve_main
{

struct HomeY
{

typedef HomeYRequest Request;
typedef HomeYResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct HomeY
} // namespace eve_main


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::eve_main::HomeY > {
  static const char* value()
  {
    return "ca65bba734a79b4a6707341d829f4d5c";
  }

  static const char* value(const ::eve_main::HomeY&) { return value(); }
};

template<>
struct DataType< ::eve_main::HomeY > {
  static const char* value()
  {
    return "eve_main/HomeY";
  }

  static const char* value(const ::eve_main::HomeY&) { return value(); }
};


// service_traits::MD5Sum< ::eve_main::HomeYRequest> should match
// service_traits::MD5Sum< ::eve_main::HomeY >
template<>
struct MD5Sum< ::eve_main::HomeYRequest>
{
  static const char* value()
  {
    return MD5Sum< ::eve_main::HomeY >::value();
  }
  static const char* value(const ::eve_main::HomeYRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::eve_main::HomeYRequest> should match
// service_traits::DataType< ::eve_main::HomeY >
template<>
struct DataType< ::eve_main::HomeYRequest>
{
  static const char* value()
  {
    return DataType< ::eve_main::HomeY >::value();
  }
  static const char* value(const ::eve_main::HomeYRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::eve_main::HomeYResponse> should match
// service_traits::MD5Sum< ::eve_main::HomeY >
template<>
struct MD5Sum< ::eve_main::HomeYResponse>
{
  static const char* value()
  {
    return MD5Sum< ::eve_main::HomeY >::value();
  }
  static const char* value(const ::eve_main::HomeYResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::eve_main::HomeYResponse> should match
// service_traits::DataType< ::eve_main::HomeY >
template<>
struct DataType< ::eve_main::HomeYResponse>
{
  static const char* value()
  {
    return DataType< ::eve_main::HomeY >::value();
  }
  static const char* value(const ::eve_main::HomeYResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // EVE_MAIN_MESSAGE_HOMEY_H
