// Generated by gencpp from file eve_main/HomeYRequest.msg
// DO NOT EDIT!


#ifndef EVE_MAIN_MESSAGE_HOMEYREQUEST_H
#define EVE_MAIN_MESSAGE_HOMEYREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace eve_main
{
template <class ContainerAllocator>
struct HomeYRequest_
{
  typedef HomeYRequest_<ContainerAllocator> Type;

  HomeYRequest_()
    : speed(0.0)  {
    }
  HomeYRequest_(const ContainerAllocator& _alloc)
    : speed(0.0)  {
  (void)_alloc;
    }



   typedef float _speed_type;
  _speed_type speed;





  typedef boost::shared_ptr< ::eve_main::HomeYRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::eve_main::HomeYRequest_<ContainerAllocator> const> ConstPtr;

}; // struct HomeYRequest_

typedef ::eve_main::HomeYRequest_<std::allocator<void> > HomeYRequest;

typedef boost::shared_ptr< ::eve_main::HomeYRequest > HomeYRequestPtr;
typedef boost::shared_ptr< ::eve_main::HomeYRequest const> HomeYRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::eve_main::HomeYRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::eve_main::HomeYRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::eve_main::HomeYRequest_<ContainerAllocator1> & lhs, const ::eve_main::HomeYRequest_<ContainerAllocator2> & rhs)
{
  return lhs.speed == rhs.speed;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::eve_main::HomeYRequest_<ContainerAllocator1> & lhs, const ::eve_main::HomeYRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace eve_main

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::eve_main::HomeYRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::eve_main::HomeYRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::eve_main::HomeYRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::eve_main::HomeYRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::eve_main::HomeYRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::eve_main::HomeYRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::eve_main::HomeYRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ca65bba734a79b4a6707341d829f4d5c";
  }

  static const char* value(const ::eve_main::HomeYRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xca65bba734a79b4aULL;
  static const uint64_t static_value2 = 0x6707341d829f4d5cULL;
};

template<class ContainerAllocator>
struct DataType< ::eve_main::HomeYRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "eve_main/HomeYRequest";
  }

  static const char* value(const ::eve_main::HomeYRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::eve_main::HomeYRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 speed\n"
;
  }

  static const char* value(const ::eve_main::HomeYRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::eve_main::HomeYRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.speed);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct HomeYRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::eve_main::HomeYRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::eve_main::HomeYRequest_<ContainerAllocator>& v)
  {
    s << indent << "speed: ";
    Printer<float>::stream(s, indent + "  ", v.speed);
  }
};

} // namespace message_operations
} // namespace ros

#endif // EVE_MAIN_MESSAGE_HOMEYREQUEST_H
