(cl:defpackage eve_main-srv
  (:use )
  (:export
   "GETPOSITION"
   "<GETPOSITION-REQUEST>"
   "GETPOSITION-REQUEST"
   "<GETPOSITION-RESPONSE>"
   "GETPOSITION-RESPONSE"
   "GOTOPOSITION"
   "<GOTOPOSITION-REQUEST>"
   "GOTOPOSITION-REQUEST"
   "<GOTOPOSITION-RESPONSE>"
   "GOTOPOSITION-RESPONSE"
  ))

